version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

  web:
    image: mywebapp:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: userpass
    depends_on:
      - db
    networks:
      - app_net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_net

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker/data/mysql
      o: bind

networks:
  app_net:
    driver: overlay